### ISSUE TITLE
[Question] How to generate types for graphql

### ISSUE THREAD

**Issue by SekibOmazic** [Urigo/WhatsApp-Clone-Client-React#157]
when running `yarn generate` I get following error (master branch):
```
⇒  yarn generate
yarn run v1.13.0
$ gql-gen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/graphql/types.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate

  Found 1 error

   ✖ ./src/graphql/types.ts
    Error: Failed to load schema

Something went wrong
error Command failed with exit code 1.
```

In `codgen.yml` schema should be read from: `schema: ../WhatsApp-Clone-Server/schema/typeDefs.ts`. But there is no such thing in the server repo (I did `yarn generate`on the server side)

What am I doing wrong?

**Comment by DAB0mB** [comment]
You should git-checkout the following branch when working with the client: https://github.com/Urigo/WhatsApp-Clone-server/tree/step-by-step
We're currently migrating some changes and soon everything should work with the master branch as well @darkbasic

**Comment by DAB0mB** [comment]
@SekibOmazic The issue is fixed. It would be nice if you could confirm that it works for you

**Comment by SekibOmazic** [comment]
@DAB0mB Works fine. Will close the issue

**Comment by Cmac2712** [comment]
I had the same issue even with the 'step-by-step' branch checked out.

It turned out to be because https://github.com/Urigo/WhatsApp-Clone-server/ has a lower case 's' in 'server' whereas in codegen.yml it's defined as 'schema: ../WhatsApp-Clone-Server/schema.ts'.

Fixed it by just renaming 'WhatsApp-Clone-server' directory to 'WhatsApp-Clone-Server' and then it was able to find the schema. 👍
