### ISSUE TITLE
Unsafe type assertion used in various places on tutorial

### ISSUE THREAD

**Issue by TVaakanainen** [Urigo/WhatsApp-Clone-Client-React#923]
For example:
const BackButton = styled(Button)`
  svg {
    color: var(--primary-text);
  }
` as typeof Button;

I think this should instead be: 
const BackButton: typeof Button = styled(Button)`
  svg {
    color: var(--primary-text);
  }
`;

Sorry about the odd visualization, didn't quickly figure out a way to escape the template-string in markdown to allow using pre-formatted text-block...

Coming back to the matter. So why I think the above way is unsafe is that using the as-assertion one basically goes around typescript-compiler, so in no scenario you will get any notice from compiler if your assertion is wrong, the latter will provide that.

Please see https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html for reference.

I know there are scenarios where avoiding as-assertion is hard and time-consuming in the way that it might not make sense, but overall I think the more one can avoid it at (almost) all cost, the better.

**Comment by Urigo** [comment]
Yes that was because of the issue mentioned [here](https://stackoverflow.com/questions/54509851/styled-components-typescript-error-with-material-ui-component#comment98797313_55906398)

But now with all the new versions we can safely remove those, thanks for reminding me!

Updated and deployed a new `next` version
